.TH TZSELECT 8
.SH NAME
tzselect \- select a time zone
.SH SYNOPSIS
.B tzselect
[
.B \-c
.I coord
] [
.B \-n
.I limit
] [
.B \-t
.I zonetabtype
] [
.B \-\-help
] [
.B \-\-version
]
.SH DESCRIPTION
The
.B tzselect
program asks the user for information about the current location,
and outputs the resulting time zone description to standard output.
The output is suitable as a value for the TZ environment variable.
.PP
All interaction with the user is done via standard input and standard error.
.SH OPTIONS
.TP
.BI "\-c " coord
Instead of asking for continent and then country and then city,
ask for selection from time zones whose largest cities
are closest to the location with geographical coordinates
.IR coord .
Use ISO 6709 notation for
.IR coord ,
for example,
.B "\-c\ \+42.391415\-071.570419"
for 42.391415\(de\|N, 71.570419\(de\|W, and
.B "\-c\ +404226\-0740319"
for 48\(de\|42\(fm\|26\(sd\|N, 74\(de\|3\(fm\|19\(sd\|W.
.TP
.BI "\-n " limit
When
.B \-c
is used, display the closest
.I limit
locations (default 10).
.TP
.BI "\-t " zonetabtype
Make selections from the time zone table of type
.IR zonetabtype .
Possible
.I zonetabtype
values include:
.RS
.TP
.B time
A time zone table with a smaller set of zone names.
.TP
.B zone
A time zone table that also contains alternative zone names, for
backward compatibility with older versions of this software.  The
alternative names are not needed for proper operation of time stamps;
they are present only to avoid surprises with people who are
accustomed to the old names.  These alternative names arose from
political issues that are outside the scope of
.BR tzselect .
.PP
For example, both tables have entries for countries like
Bosnia, Croatia, and Serbia, which are in a zone where the clocks
have all agreed since 1970.  Although the
.B time
table lists "Europe/Belgrade" for this zone wherever it occurs, the
.B zone
table instead lists the names "Europe/Sarajevo", "Europe/Zagreb",
etc. under Bosnia, Croatia, etc.  This means that the
.B "\-t\ time"
option causes
.B tzselect
to generate "Europe/Belgrade" for this zone, whereas
.B "\-t\ zone"
causes it to generate different names depending on the country,
names that are equivalent in effect to "Europe/Belgrade".
.PP
The default
.I zonetabtype
is system-dependent, so applications that care about the set of
names that
.B tzselect
generates should use the
.B "\-t"
option.  Regardless of what options are used, applications should not
assume that
.BR tzselect 's
output matches the user's political preferences.
.RE
.TP
.B "\-\-help"
Output help information and exit.
.TP
.B "\-\-version"
Output version information and exit.
.SH "ENVIRONMENT VARIABLES"
.TP
\f3AWK\fP
Name of a Posix-compliant
.I awk
program (default:
.BR awk ).
.TP
\f3TZDIR\fP
Name of the directory containing time zone data files (default:
.BR /usr/local/etc/zoneinfo ).
.SH FILES
.TP
\f2TZDIR\fP\f3/iso3166.tab\fP
Table of ISO 3166 2-letter country codes and country names.
.TP
\f2TZDIR\fP\f3/time.tab\fP
.TP
\f2TZDIR\fP\f3/zone.tab\fP
Tables of country codes, latitude and longitude, zone names, and
descriptive comments.
.TP
\f2TZDIR\fP\f3/\fP\f2TZ\fP
Time zone data file for time zone \f2TZ\fP.
.SH "EXIT STATUS"
The exit status is zero if a time zone was successfully obtained from the user,
nonzero otherwise.
.SH "SEE ALSO"
newctime(3), tzfile(5), zdump(8), zic(8)
.\" This file is in the public domain, so clarified as of
.\" 2009-05-17 by Arthur David Olson.
